# Generated by Django 5.0.6 on 2024-05-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.CharField(default='Описание по умолчанию', max_length=400),
        ),
    ]
