# Generated by Django 5.0.6 on 2024-05-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_driver_age_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='articles',
            field=models.ManyToManyField(related_name='reviews', to='main.article'),
        ),
    ]
