# Generated by Django 5.0.6 on 2024-05-26 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_review_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='articles',
        ),
    ]
