# Generated by Django 5.0.6 on 2024-05-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_review_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('company_owner', 'Company Owner')], default='client', max_length=20),
        ),
    ]
