# Generated by Django 5.0.6 on 2024-05-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.company'),
        ),
    ]
