# Generated by Django 5.0.6 on 2024-05-27 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_clientprofile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='vehicle',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_set', to='main.clientprofile'),
        ),
    ]
