# Generated by Django 5.0.6 on 2024-05-27 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_vehicle_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cargo_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_driver', to='main.clientprofile'),
        ),
    ]
