# Generated by Django 5.0.6 on 2024-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_faq_term_clientprofile_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='text',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
