# Generated by Django 5.0.6 on 2024-05-29 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_order_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='birthday',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
